services:
  web:
    build:
      context: .
      dockerfile: app/Dockerfile
    image: mugalimder_web:latest
    env_file:
      - ./env/app.env
    depends_on:
      - db
    volumes:
      - ./src:/app/src
      - ./volumes/static:/app/staticfiles
      - ./volumes/media:/app/mediafiles
    restart: unless-stopped

  db:
    image: postgres:16
    env_file:
      - ./env/db.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  nginx:
    image: nginx:1.27-alpine
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d:ro
      - ./volumes/static:/vol/static:ro
      - ./volumes/media:/vol/media:ro
      - /home/deploy/mugalimder/volumes/letsencrypt:/etc/letsencrypt
      - /home/deploy/mugalimder/volumes/certbot-webroot:/var/www/certbot
    restart: unless-stopped

volumes:
  pgdata:
